-- 6.2.- VISUALIZAR EL NUMDE DE TODOS LOS EMPLEADOS QUE PERCIBEN LOS 3 MENORES SALARIOS(3 min salar) DE CADA NUMDE.

DECLARE
  CURSOR C IS SELECT DISTINCT NUMDE FROM TEMPLE;
  LINEA_C C%ROWTYPE;
  CURSOR CMAX(dept temple.numde%type) IS SELECT DISTINCT SALAR  from temple where numde=dept  ORDER BY SALAR;
  LINEA_CMAX CMAX%ROWTYPE;
  CURSOR C1(dept temple.numde%type, salario temple.salar%type)   IS SELECT NOMEM, NUMDE, SALAR FROM TEMPLE  where numde=dept and salar=salario;
  LINEA_C1 C1%ROWTYPE;
  CONTADORSALARIOS NUMBER:=0;
BEGIN
  OPEN C;
  FETCH C INTO LINEA_C;
  WHILE C%FOUND LOOP 
   DBMS_OUTPUT.PUT_LINE('****** DEPARTAMENTO '||LINEA_C.NUMDE);
     CONTADORSALARIOS :=0;
     OPEN CMAX(LINEA_C.NUMDE);
     FETCH CMAX INTO LINEA_CMAX;
     WHILE CMAX%FOUND AND CONTADORSALARIOS<3  LOOP 
           OPEN C1(LINEA_C.NUMDE,LINEA_CMAX.SALAR);
           FETCH C1 INTO LINEA_C1;
           WHILE C1%FOUND  LOOP  
               DBMS_OUTPUT.PUT_LINE(LINEA_C1.NOMEM||'  '||LINEA_C1.salar);
               FETCH C1 INTO LINEA_C1;
           END LOOP;
            CONTADORSALARIOS:=CONTADORSALARIOS+1;
            CLOSE C1;
      FETCH CMAX INTO LINEA_CMAX;
      END LOOP;
      CLOSE CMAX;
  FETCH C INTO LINEA_C;
  END LOOP;
  CLOSE C;
END;
