-- 1.- PROGRAMAR UN BLOQUE ANONIMO QUE VISUALICE EL NOMEM, FECIN Y UN TERCIO DEL SALAR, DE TODOS LOS EMPLEADOS QUE TIENEN COMISIÓN, ORDENADOS POR NOMEM.

SET SERVEROUTPUT ON;
DECLARE
  CURSOR C1 IS SELECT NOMEM, FECIN FROM TEMPLE ORDER BY NOMEM;  
BEGIN
  FOR LINEA_C1 IN C1 LOOP
    DBMS_OUTPUT.PUT_LINE('Empleado: ' || LINEA_C1.NOMEM || '  Fecha de alta: ' || LINEA_C1.FECIN);    
  END LOOP;  
END;
