-- 3.1.- VISUALIZAR EL NUMDE Y DOS EMPLEADOS DE CADA NUMDE.

SET SERVEROUTPUT ON;
DECLARE
  CURSOR C1 IS SELECT NOMEM, NUMDE FROM TEMPLE ORDER BY NUMDE;
  LINEA_C1 C1%ROWTYPE;
  CONTADOR NUMBER:=0;
  AUX TEMPLE.NUMDE%TYPE;
BEGIN
  OPEN C1;
  FETCH C1 INTO LINEA_C1;
  WHILE C1%FOUND LOOP
     DBMS_OUTPUT.PUT_LINE('Departamento '||LINEA_C1.numde); 
     CONTADOR:=0;
     AUX:= LINEA_C1.NUMDE;
     WHILE C1%FOUND AND AUX=LINEA_C1.NUMDE LOOP
            IF CONTADOR < 2 THEN
                     CONTADOR := CONTADOR +1;
                     DBMS_OUTPUT.PUT_LINE(LINEA_C1.NOMEM);
            END IF;
        FETCH C1 INTO LINEA_C1;
     END LOOP;
  END LOOP;
  CLOSE C1;
END;
