-- 3.2.- VISUALIZAR EL NUMDE Y DOS EMPLEADOS DE CADA NUMDE.

SET SERVEROUTPUT ON;
DECLARE
  CURSOR C1 IS SELECT NOMEM, NUMDE FROM TEMPLE ORDER BY NUMDE;
  LINEA_C1 C1%ROWTYPE;
  CONTADOR NUMBER:=0;
  AUX TEMPLE.NUMDE%TYPE;
BEGIN
  OPEN C1;
  FETCH C1 INTO LINEA_C1;
  WHILE C1%FOUND LOOP
     -- INICIO DE RUPTURA 
     CONTADOR:=0;
     AUX:= LINEA_C1.NUMDE;
     WHILE C1%FOUND AND AUX=LINEA_C1.NUMDE  AND CONTADOR < 2 LOOP
        CONTADOR := CONTADOR +1;
        DBMS_OUTPUT.PUT_LINE(LINEA_C1.NOMEM||'  '||AUX);
            
        FETCH C1 INTO LINEA_C1;
     END LOOP;
     -- FUERZO QUE CAMBIE DE NUMDE CUANDO ESTOY EN EL MISMO NUMDE Y YA HE TRATADO 2
     WHILE C1%FOUND AND AUX=LINEA_C1.NUMDE LOOP
        FETCH C1 INTO LINEA_C1;
     END LOOP;
     -- RUPTURA POR CAMBIO DE NUMDE
     
  END LOOP;
  CLOSE C1;
END;
