-- 4.- VISUALIZAR NUMDE Y TODOS LOS EMPLEADOS QUE MENOS GANAN (min salar) DE CADA NUMDE.

SET SERVEROUTPUT ON;
DECLARE
  CURSOR C1 IS SELECT NOMEM, NUMDE, SALAR FROM TEMPLE ORDER BY NUMDE, SALAR;
  LINEA_C1 C1%ROWTYPE;
  AUX TEMPLE.NUMDE%TYPE;
  AUX2 TEMPLE.SALAR%TYPE;
BEGIN
  OPEN C1;
  FETCH C1 INTO LINEA_C1;
  WHILE C1%FOUND LOOP
     AUX:= LINEA_C1.NUMDE;
     AUX2:= LINEA_C1.SALAR;
     WHILE C1%FOUND AND AUX=LINEA_C1.NUMDE LOOP
            IF AUX2= LINEA_C1.SALAR THEN
             DBMS_OUTPUT.PUT_LINE(LINEA_C1.NOMEM||'  '||AUX2||'  '||LINEA_C1.NUMDE);
               END IF;
        FETCH C1 INTO LINEA_C1;
     END LOOP;
  END LOOP;
  CLOSE C1;
END;
